splits:
  train_months: 18
  val_months: 2
  test_months: 2
  oot_months: 2

# cv_folds: 2
# search_n_iter: 10
# search_random_state: 42

lgbm_base_params:
  objective: regression
  metric: rmse
  boosting_type: gbdt
  random_state: 42
  n_jobs: -1
  verbose: -1

# RandomizedSearchCV will sample uniformly from these candidate lists
# lgbm_param_distributions:
#   n_estimators: [100, 200, 300]
#   learning_rate: [0.03, 0.05, 0.07]
#   num_leaves: [31, 63]
#   max_depth: [4, 6]
#   min_child_samples: [20, 50, 100]
#   subsample: [0.7, 0.8, 0.9, 1.0]             # bagging_fraction
#   colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0] # feature_fraction
#   reg_alpha: [0.0, 0.1, 0.3, 0.5, 1.0]
#   reg_lambda: [0.0, 0.1, 0.3, 0.5, 1.0]
#   min_split_gain: [0.0, 0.01, 0.05, 0.1]

evaluation_metrics:
  - rmse
  - mae
  - r2

target_col: label_next_month_sales
join_keys: ["store_nbr", "family"]

categorical_features:
  - store_nbr
  - family

numerical_features:
  - num_holidays_total
  - num_transferred
  - num_holidays_type_Event
  - num_holidays_type_Holiday
  - num_holidays_type_Transfer
  - num_holidays_type_Bridge
  - num_holidays_type_Additional
  - num_holidays_type_Work Day
  - num_holidays_locale_National
  - num_holidays_locale_Local
  - num_holidays_locale_Regional
  - num_holidays_total_NM
  - num_transferred_NM
  - num_holidays_type_Event_NM
  - num_holidays_type_Holiday_NM
  - num_holidays_type_Transfer_NM
  - num_holidays_type_Bridge_NM
  - num_holidays_type_Additional_NM
  - num_holidays_type_Work Day_NM
  - num_holidays_locale_National_NM
  - num_holidays_locale_Local_NM
  - num_holidays_locale_Regional_NM
  - sales_LM
  - AVG_sales_L3M
  - SUM_sales_L3M
  - onpromotion_LM
  - AVG_onpromotion_L3M
  - SUM_onpromotion_L3M
  - transactions_LM
  - AVG_transactions_L3M
  - SUM_transactions_L3M
  - AVG_dcoilwtico_LM
  - AVG_dcoilwtico_L3M
  - SUM_dcoilwtico_L3M