# =========================
# Monitoring Configuration
# =========================

# --- 0. Deployment controls -----------------------------
deployment_date: "2015-06-01"   # First model deployment date
# First monitoring date = deployment_date + 1 month

# --- 1. Performance Monitoring --------------------------
performance_monitoring:
  # These thresholds compare current-month performance vs the deployed model's OOT baseline.
  thresholds:
    r2_drop_allowed: 0.10       # e.g., current R² can be at most 0.10 below baseline R²
    rmse_increase_ratio: 1.25   # e.g., RMSE can be at most +25% vs baseline
    mae_increase_ratio: 1.25    # e.g., MAE can be at most +25% vs baseline

# --- 2. Drift Monitoring (PSI/CSI) ----------------------
drift_monitoring:
  variables:
    - AVG_sales_L3M
    - num_holidays_total
    - transactions_LM
    - sales_LM
    - num_holidays_type_Additional
    - AVG_dcoilwtico_LM
    - num_holidays_total_NM
    - onpromotion_LM
    - num_holidays_locale_Regional_NM
    - num_holidays_type_Holiday
  n_bins: 10
  bin_method: quantile   # quantile | uniform

# --- 2a. PSI (Population Stability Index) ---------------
psi_monitoring:
  # Three-tier drift thresholds
  psi_thresholds:
    stable: 0.10        # < 0.10 → stable
    moderate: 0.25      # 0.10–0.25 → moderate drift
    significant: 0.25   # > 0.25 → significant drift

# --- 3. CSI (Characteristic Stability Index) ------------
csi_monitoring:
  csi_thresholds:
    stable: 0.10        # < 0.10 → stable
    moderate: 0.25      # 0.10–0.25 → moderate drift
    significant: 0.25   # > 0.25 → significant drift
